.TH ellipsis 1 "4 November 2018" 0.1.0
.SH NAME
ellipsis-git - share configurations with git

.SH SYNOPSIS
ellipsis git
[
.I options
]

.SH DESCRIPTION
This command forwards all given arguments to the git command, executed in the
context of the ellipsis home directory. This command is functionally equivalent
to invoking git -C $(ellipsis home) [
.I options
]

.SH AUTHOR
Andrew Lee

.SH BUGS
Report any bugs on github: <https://github.com/ndrewtl/ellipsis>

.SH COPYRIGHT
Copyright (C) 2018 Andrew Lee. Licensed under GNU General Public License,
version 3. <https://www.gnu.org/licenses/gpl.html>

.SH SEE ALSO
ellipsi(1), git(1), pass(1)
