.TH ellipsis 1 "5 November 2018" 0.1.0
.SH NAME
ellipsis-init - share configurations with git

.SH SYNOPSIS
ellipsis-init
[
.I URI
]

.SH DESCRIPTION
Initializes the ellipsis home directory. This is the first command you should
use on any new machine. If you haven't created an ellipsis configuration
directory before, use:

ellipsis init

to create a new git repository. This is akin to calling:

git init $(ellipsis home)

Given
.I URI
identifying some local or remote git repository, this command clones the given
repository into the ellipsis home directory. This is akin to calling:

git clone URI $(ellipsis home)

This command will do nothing and exit with an error message if the ellipsis home
directory already exists.

.SH AUTHOR
Andrew Lee

.SH BUGS
Report any bugs on github: <https://github.com/ndrewtl/ellipsis>

.SH COPYRIGHT
Copyright (C) 2018 Andrew Lee. Licensed under GNU General Public License,
version 3. <https://www.gnu.org/licenses/gpl.html>

.SH SEE ALSO
ellipsis(1), git-clone(1)
