.TH ellipsis 1 "5 November 2018" 0.1.0
.SH NAME
ellipsis-init - share configurations with git

.SH SYNOPSIS
ellipsis-init
[
.I URI
]

.SH DESCRIPTION
Given
.I URI
identifying some local or remote git repository, this command clones the given
rerepository into the ellipsis home directory.

.SH AUTHOR
Andrew Lee

.SH BUGS
Report any bugs on github: <https://github.com/ndrewtl/ellipsis>

.SH COPYRIGHT
Copyright (C) 2018 Andrew Lee. Licensed under GNU General Public License,
version 3. <https://www.gnu.org/licenses/gpl.html>

.SH SEE ALSO
ellipsis(1), git-clone(1)
